#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d                         1 2 3 4 5 6 7 8 9

bspc config border_width                2
bspc config window_gap                  8

bspc config normal_border_color         "#0A1F32"
bspc config active_border_color         "#2D384A"
bspc config focused_border_color        "#344756"

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config focus_follows_pointer       true
bspc config gapless_monocle             true

bspc config single_monocle              true
bspc config borderless_monocle          true
